### ISSUE TITLE
Russian rouble gliph in pre-lollipop android 

### ISSUE THREAD

**Issue by ray1984** [johnkil/Android-RobotoTextView#41]
I found a problem that pre-lollipop android versions don't have russian rouble sign (\u20bd). Can you update fonts on https://www.google.com/fonts/specimen/Roboto - it has necessary symbol

**Comment by ray1984** [comment]
https://github.com/johnkil/Android-RobotoTextView/pull/42

**Comment by johnkil** [comment]
Depends on https://github.com/johnkil/Android-RobotoTextView/issues/40
