### ISSUE TITLE
Not compiles if compileSdk/targetSdk was set lower than 23

### ISSUE THREAD

**Issue by VyacheslavShmakin** [johnkil/Android-RobotoTextView#44]
Project can't be compiled if compileSdk/targetSdk was set lower than 23. It happens on 2.4.1 version also. But 2.4.0 version can be compiled successfuly.

So, I'm getting an error message:
...\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.0\res\values-v23\values-v23.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

**Comment by johnkil** [comment]
@VyacheslavShmakin compileSdk version must be 23 and above if you use AppCompat v23+.

**Comment by VyacheslavShmakin** [comment]
Well, I'm using AppCompat v22.2.1

**Comment by johnkil** [comment]
Android-RobotoTextView is using AppCompat v23+.

**Comment by VyacheslavShmakin** [comment]
oh... got it. Thanks

**Comment by johnkil** [comment]
:wink:
