### ISSUE TITLE
Add support for "smallcaps" typeface

### ISSUE THREAD

**Issue by Saketme** [johnkil/Android-RobotoTextView#46]
I'm seeing a new `fontFamily: sans-serif-smallcaps` in my project. I'm guessing this was added in Lollipop. 

The font used is a non Roboto font, but I was wondering if it could be added to this library. I'd not prefer using another library just for that font :)

**Update: ** The font is `CarroisGothicSC-Regular`

**Comment by johnkil** [comment]
Thank you for your interest in the project ))
Main idea of project is "Implementation of a TextView and all its direct/indirect subclasses with native support for the Roboto fonts". I would not want to inflate the project with additional fonts and code.  I hope you understand me ;)

**Comment by Saketme** [comment]
Was expecting this reply :( Thank you anyway.
