### ISSUE TITLE
Exactly how to remove extra font?

### ISSUE THREAD

**Issue by pkb126** [johnkil/Android-RobotoTextView#52]
I tried to put your code in gradle file but it's not working means not removing font.

So, can you please elaborate how to remove extra font.

**Comment by johnkil** [comment]
Which version do you use?

**Comment by pkb126** [comment]
gradle 2.2.3

**Comment by johnkil** [comment]
no for Android-RobotoTextView

**Comment by pkb126** [comment]
2.5.0

**Comment by johnkil** [comment]
try to use last version 2.5.1 :)

**Comment by pkb126** [comment]
will try soon, check it. Thank you

**Comment by johnkil** [comment]
😉
