### ISSUE TITLE
AAPT fails when using both RobotoTextView library and AppCompat library

### ISSUE THREAD

**Issue by dennisdrew** [johnkil/Android-RobotoTextView#60]
With appcompat-v7 version 26+, both RobotoTextView and AppCompatTextView attempt to declare

```
<attr name="fontFamily">
```
However, for AppCompat its format is "string", whereas for RobotoTextView it's "enum"

Gradle build will fail with something like

```
/Users/ddennis/project/app/build/intermediates/res/merged/release/values/values.xml:194: error: Attribute "fontFamily" already defined with incompatible format.
/Users/ddennis/project/app/build/intermediates/res/merged/release/values/values.xml:5: Original attribute defined here.
```

**Comment by dennisdrew** [comment]
Didn't see latest commit. Updated to v4.0.0 and build works. Good work, johnkil!

**Comment by johnkil** [comment]
😉
